# Web Scraping dengan API (JSONPlaceholder)

**Target:** REST API publik `https://jsonplaceholder.typicode.com`

**Anggota Kelompok:**
1. Akram Ali Fi Natarik (25031554212)
2. M. Furqon Lutfi Septriandri (25031554192)

Alur yang dipakai: 
- request endpoint 
- cek status 
- lihat struktur JSON 
- ubah jadi DataFrame 
- jelajahi endpoint terkait 
- pakai query parameter 
- loop banyak data 
- simpan & baca ulang file JSON.

## 1. Import Library

In [1]:
import requests
import pandas as pd
import json

## 2. Request Endpoint /posts & Cek Status Code

In [2]:
api_url = "https://jsonplaceholder.typicode.com/posts"
response = requests.get(api_url)
response.status_code

200

## 3. Lihat Struktur Data JSON

In [3]:
data = response.json()  # otomatis parsing JSON jadi list of dict
data[0]

{'userId': 1,
 'id': 1,
 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit',
 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}

## 4. Tampilkan 5 Data Pertama

In [4]:
for item in data[:5]:
    print(f"ID: {item['id']} | Judul: {item['title']}")

ID: 1 | Judul: sunt aut facere repellat provident occaecati excepturi optio reprehenderit
ID: 2 | Judul: qui est esse
ID: 3 | Judul: ea molestias quasi exercitationem repellat qui ipsa sit aut
ID: 4 | Judul: eum et est occaecati
ID: 5 | Judul: nesciunt quas odio

## 5. Ubah Seluruh Data Menjadi DataFrame

In [5]:
df_posts = pd.DataFrame(data)
df_posts.head(10)

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...
5,1,6,dolorem eum magni eos aperiam quia,ut aspernatur corporis harum nihil quis provid...
6,1,7,magnam facilis autem,dolore placeat quibusdam ea quo vitae\nmagni q...
7,1,8,dolorem dolore est ipsam,dignissimos aperiam dolorem qui eum\nfacilis q...
8,1,9,nesciunt iure omnis dolorem tempora et accusan...,consectetur animi nesciunt iure dolore\nenim q...
9,1,10,optio molestias id quia eum,quo et expedita modi cum officia vel magni\ndo...

## 6. Ambil Data dari Endpoint Terkait

In [6]:
post_id = 1
url_comments = f"https://jsonplaceholder.typicode.com/posts/{post_id}/comments"
comments = requests.get(url_comments).json()
comments[:2]

[{'postId': 1,
  'id': 1,
  'name': 'id labore ex et quam laborum',
  'email': 'Eliseo@gardner.biz',
  'body': 'laudantium enim quasi est quidem magnam voluptate ipsam eos\ntempora quo necessitatibus\ndolor quam autem quasi\nreiciendis et nam sapiente accusantium'},
 {'postId': 1,
  'id': 2,
  'name': 'quo vero reiciendis velit similique earum',
  'email': 'Jayne_Kuhic@sydney.com',
  'body': 'est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et'}]

## 7. Ubah Data Comments Menjadi DataFrame

In [7]:
df_comments = pd.DataFrame(comments)
df_comments

,postId,id,name,email,body
0,1,1,id labore ex et quam laborum,Eliseo@gardner.biz,laudantium enim quasi est quidem magnam volupt...
1,1,2,quo vero reiciendis velit similique earum,Jayne_Kuhic@sydney.com,est natus enim nihil est dolore omnis voluptat...
2,1,3,odio adipisci rerum aut animi,Nikita@garfield.biz,quia molestiae reprehenderit quasi aspernatur\...
3,1,4,alias odio sit,Lew@alysha.tv,non et atque\noccaecati deserunt quas accusant...
4,1,5,vero eaque aliquid doloribus et culpa,Hayden@althea.biz,harum non quasi et ratione\ntempore iure ex vo...

## 8. Gunakan Query Parameter untuk Filter Data

In [8]:
response_filtered = requests.get(
    "https://jsonplaceholder.typicode.com/comments",
    params={"postId": 1}
)
response_filtered.json()[:2]

[{'postId': 1,
  'id': 1,
  'name': 'id labore ex et quam laborum',
  'email': 'Eliseo@gardner.biz',
  'body': 'laudantium enim quasi est quidem magnam voluptate ipsam eos\ntempora quo necessitatibus\ndolor quam autem quasi\nreiciendis et nam sapiente accusantium'},
 {'postId': 1,
  'id': 2,
  'name': 'quo vero reiciendis velit similique earum',
  'email': 'Jayne_Kuhic@sydney.com',
  'body': 'est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et'}]

## 9. Loop untuk Ambil Ringkasan Beberapa Post Sekaligus

In [9]:
ringkasan = []

for pid in range(1, 6):
    post = requests.get(f"https://jsonplaceholder.typicode.com/posts/{pid}").json()
    komentar = requests.get(f"https://jsonplaceholder.typicode.com/posts/{pid}/comments").json()
    ringkasan.append({
        "postId": pid,
        "title": post["title"],
        "jumlah_komentar": len(komentar)
    })

ringkasan

[{'postId': 1,
  'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit',
  'jumlah_komentar': 5},
 {'postId': 2, 'title': 'qui est esse', 'jumlah_komentar': 5},
 {'postId': 3,
  'title': 'ea molestias quasi exercitationem repellat qui ipsa sit aut',
  'jumlah_komentar': 5},
 {'postId': 4, 'title': 'eum et est occaecati', 'jumlah_komentar': 5},
 {'postId': 5, 'title': 'nesciunt quas odio', 'jumlah_komentar': 5}]

## 10. Ubah Ringkasan Menjadi DataFrame

In [10]:
df_ringkasan = pd.DataFrame(ringkasan)
df_ringkasan

   postId                                              title  jumlah_komentar
0       1  sunt aut facere repellat provident occaecati e...                5
1       2                                       qui est esse                5
2       3  ea molestias quasi exercitationem repellat qui...                5
3       4                               eum et est occaecati                5
4       5                                 nesciunt quas odio                5

## 11. Simpan Hasil Scraping ke File JSON

In [13]:
with open("hasil scraping posts.json", "w") as f:
    json.dump(data, f, indent=4)

print("Tersimpan sebagai hasil scraping posts.json")

Tersimpan sebagai hasil scraping posts.json

## 12. Baca Kembali File JSON yang Sudah Disimpan

In [12]:
with open("hasil_scraping_posts.json", "r") as f:
    data_loaded = json.load(f)

len(data_loaded)

100